---
name: "issue-metrics-test"
author: "github-test"
description: "A GitHub Action to report out issue metrics"
runs:
  using: "docker"
  image: "docker://ghcr.io/github/issue_metrics:v3"
branding:
  icon: "check-square"
  color: "white"
